timer:
  dishwasher_delayed_job_completion_timer:
    name: Dishwasher - Delayed Job Completion Timer
    duration: "00:15:00" # <- Note that the time here. Leave as it is (15 min)
    restore: true
    icon: mdi:dishwasher

input_boolean:
  dishwasher_job_cycle:
    name: Dishwasher - Job Cycle
    icon: mdi:dishwasher

  dishwasher_automation_self_trigger:
    name: Dishwasher - Automation Self-trigger
    icon: mdi:dishwasher

input_select:
  dishwasher_state_machine:
    name: Dishwasher - State Machine
    options:
      - unplugged
      - idle
      - paused
      - detached_overload
      - job_ongoing
      - job_completed
    icon: mdi:dishwasher

sensor:
  - name: Dishwasher Time Today
    platform: history_stats    
    entity_id: input_select.dishwasher_state_machine
    state: "job_ongoing"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - name: Dishwasher Cycles Today
    platform: history_stats    
    entity_id: input_select.dishwasher_state_machine
    state: "job_completed"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

template:
  - sensor:
      - name: Dishwasher Cycles Available
        unique_id: sensor.dishwasher_cycles_available
        icon: mdi:dishwasher
        unit_of_measurement: 'cyc'
        state: >-
          {% set energy_per_cycle=1.1 %}
          {% set surplus_capacity=states.binary_sensor.battery_non_viability.attributes.surplus_capacity %}
          {{ (surplus_capacity/energy_per_cycle) | round(0,'floor') }}