- id: '1675016443917'
  alias: Attic Power Toggle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.attic_study_power
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.attic_study_power
      state: 'on'
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.attic_on
      metadata: {}
    else:
    - if:
      - condition: state
        entity_id: input_boolean.attic_study_power
        state: 'off'
      then:
      - service: script.graceful_shutdown
        data: {}
  mode: single
- id: '1677542848958'
  alias: Home Energy Carbon Split
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.home_energy
  condition:
  - condition: template
    value_template: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
      | float -%}

      {{ delta > 0 }}'
  action:
  - service: input_number.set_value
    data:
      value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
        | float -%} {%- set current_energy = states("input_number.energy_fossil_home")
        | float -%} {{ current_energy + delta * 0.01 * (states("sensor.co2_signal_grid_fossil_fuel_percentage")
        | float)  }}'
    target:
      entity_id: input_number.energy_fossil_home
  - service: input_number.set_value
    data:
      value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
        | float -%} {%- set current_energy = states("input_number.energy_low_carbon_home")
        | float -%} {{ current_energy + delta * 0.01 * (100 - (states("sensor.co2_signal_grid_fossil_fuel_percentage")
        | float))  }}'
    target:
      entity_id: input_number.energy_low_carbon_home
  - service: input_number.set_value
    data:
      value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
        | float -%} {%- set current_carbon = states("input_number.carbon_footprint_home")
        | float -%} {{ current_carbon + 0.001 * delta * (states("sensor.co2_signal_co2_intensity")
        | float)  }}'
    target:
      entity_id: input_number.carbon_footprint_home
  - service: input_number.set_value
    data:
      value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
        | float -%} {%- set current_cost = states("input_number.cost_home") | float
        -%} {{ current_cost + delta * (states("sensor.octopus_energy_electricity_16p7133293_1012800425985_current_rate")
        | float)  }}'
    target:
      entity_id: input_number.cost_home
  - if:
    - condition: state
      entity_id: binary_sensor.octopus_intelligent_slot
      state: 'on'
    then:
    - service: input_number.set_value
      data:
        value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
          | float -%} {%- set current_energy = states("input_number.home_off_peak_energy")
          | float -%} {{ current_energy + delta }}'
      target:
        entity_id: input_number.home_off_peak_energy
    - service: input_number.set_value
      data:
        value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
          | float -%} {%- set current_cost = states("input_number.home_off_peak_cost")
          | float -%} {{ current_cost + delta * 0.075  }}'
      target:
        entity_id: input_number.home_off_peak_cost
    else:
    - service: input_number.set_value
      data:
        value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
          | float -%} {%- set current_energy = states("input_number.home_peak_energy")
          | float -%} {{ current_energy + delta }}'
      target:
        entity_id: input_number.home_peak_energy
    - service: input_number.set_value
      data:
        value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
          | float -%} {%- set current_cost = states("input_number.home_peak_cost")
          | float -%} {{ current_cost + delta * 0.401  }}'
      target:
        entity_id: input_number.home_peak_cost
  mode: single
- id: '1680374296097'
  alias: Home Internal Consumption Split
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.home_internal_consumption
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
        | float -%}  {%- set current_internal = states("input_number.home_internal_consumption")
        | float -%}  {%- if delta > 0 -%} {{ current_internal + delta  }} {%- else
        -%} {{ current_internal }} {%- endif -%}'
    target:
      entity_id: input_number.home_internal_consumption
  - service: input_number.set_value
    data:
      value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
        | float -%} {%- set current_carbon = states("input_number.home_shadow_carbon_footprint")
        | float -%}  {%- if delta > 0 -%} {{ current_carbon + 0.001 * delta * (states("sensor.co2_signal_co2_intensity")
        | float)  }} {%- else -%} {{ current_carbon }} {%- endif -%}'
    target:
      entity_id: input_number.home_shadow_carbon_footprint
  - service: input_number.set_value
    data:
      value: '{%- set delta = trigger.to_state.state | float - trigger.from_state.state
        | float -%} {%- set current_cost = states("input_number.home_shadow_cost")
        | float -%} {%- if delta > 0 -%} {{ current_cost + delta * (states("sensor.octopus_energy_electricity_16p7133293_1012800425985_current_rate")
        | float)  }} {%- else -%} {{ current_cost }} {%- endif -%}'
    target:
      entity_id: input_number.home_shadow_cost
  mode: single
- id: '1697985195881'
  alias: Tumble Dryer power activity
  description: Monitors tumble dryer status
  use_blueprint:
    path: leofabri/appliance-status-monitor.yaml
    input:
      appliance_socket: switch.tumble_dryer
      appliance_power_sensor: sensor.tumble_dryer_current_power
      appliance_state_machine: input_select.tumble_dryer_state_machine
      appliance_job_cycle: input_boolean.tumble_dryer_job_cycle
      delayed_job_completion_timer: timer.tumble_dryer_delayed_job_completion_timer
      automation_self_trigger: input_boolean.tumble_dryer_automation_self_trigger
      delayed_job_completion_duration: 0
      appliance_finishing_power_threshold: 1
- id: '1697985676135'
  alias: Air Fryer power activity
  description: ''
  use_blueprint:
    path: leofabri/appliance-status-monitor.yaml
    input:
      appliance_socket: switch.misc
      appliance_power_sensor: sensor.misc_current_power
      appliance_state_machine: input_select.air_fryer_state_machine
      appliance_job_cycle: input_boolean.air_fryer_job_cycle
      delayed_job_completion_timer: timer.air_fryer_delayed_job_completion_timer
      automation_self_trigger: input_boolean.air_fryer_automation_self_trigger
      delayed_job_completion_duration: 60
- id: '1697985837628'
  alias: Dishwasher power activity
  description: ''
  use_blueprint:
    path: leofabri/appliance-status-monitor.yaml
    input:
      appliance_socket: switch.dishwasher
      appliance_power_sensor: sensor.dishwasher_current_power
      appliance_state_machine: input_select.dishwasher_state_machine
      appliance_job_cycle: input_boolean.dishwasher_job_cycle
      delayed_job_completion_timer: timer.dishwasher_delayed_job_completion_timer
      automation_self_trigger: input_boolean.dishwasher_automation_self_trigger
      delayed_job_completion_duration: 0
      appliance_finishing_power_threshold: 1
- id: '1697985955021'
  alias: Washing Machine power activity
  description: ''
  use_blueprint:
    path: leofabri/appliance-status-monitor.yaml
    input:
      appliance_socket: switch.washing_machine
      appliance_power_sensor: sensor.washing_machine_current_power
      appliance_state_machine: input_select.washing_machine_state_machine
      appliance_job_cycle: input_boolean.washing_machine_job_cycle
      delayed_job_completion_timer: timer.washing_machine_delayed_job_completion_timer
      automation_self_trigger: input_boolean.washing_machine_automation_self_trigger
      delayed_job_completion_duration: 0
- id: '1697987944677'
  alias: Cooker power activity
  description: ''
  use_blueprint:
    path: leofabri/appliance-status-monitor.yaml
    input:
      appliance_socket: switch.dishwasher
      appliance_power_sensor: sensor.cooker_3_1min
      appliance_job_cycle: input_boolean.cooker_job_cycle
      appliance_state_machine: input_select.cooker_state_machine
      delayed_job_completion_timer: timer.cooker_delayed_job_completion_timer
      automation_self_trigger: input_boolean.cooker_automation_self_trigger
      delayed_job_completion_duration: 0
- id: '1698102982015'
  alias: Sync lava lamp with sofa front lamp
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: d05c9d2507155da9b10ad8b4141a1ed7
    entity_id: 4ebcc930d5f2e6209ed303eef5e698ed
    domain: light
  condition: []
  action:
  - if:
    - condition: device
      type: is_off
      device_id: d05c9d2507155da9b10ad8b4141a1ed7
      entity_id: 4ebcc930d5f2e6209ed303eef5e698ed
      domain: light
    then:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.charging_socket
    else:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.charging_socket
  mode: single
- id: '1698274812007'
  alias: Reload Emporia Vue
  description: If the cooker real-time power sensor goes offline, reload the Emporia
    Vue configuration
  trigger:
  - platform: state
    entity_id:
    - sensor.cooker_3_1min
    to: unavailable
  condition: []
  action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id: 7b65104762e00030c99ffba8adb37c59
  mode: single
- id: '1699727729502'
  alias: Mac mini status lamp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.gareths_mac_mini_camera_in_use
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.gareths_mac_mini_camera_in_use
    from: 'on'
    to: 'off'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.gareths_mac_mini_camera_in_use
      state: 'on'
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.mac_mini_camera_active
      metadata: {}
  - if:
    - condition: state
      entity_id: binary_sensor.gareths_mac_mini_camera_in_use
      state: 'off'
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.mac_mini_camera_inactive
      metadata: {}
  mode: single
- id: '1700263955237'
  alias: Front Doorbell
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: af82067c3edd79bc6f1c7652e9ad061b
    entity_id: 9cc1c9e056049009e5344c65f88d647a
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_gareths_iphone
    data:
      message: Test message.
      title: Front Doorbell
      data:
        image: http://192.168.2.64/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCel9WG79&user=admin&password=5np3xX77C!9Gyc4K
        entity_id: camera.192_168_2_64
        actions:
        - action: URI
          title: Open Cameras
          uri: http://192.168.1.5:8123/lovelace-tablet/secure
  mode: single
