## Sensors, helpers and automations to manage Octopus power up slots
## Helpers
input_datetime:
  octopus_power_up_start:
    name: Octopus Power-up start
    icon: "mdi:clock-start"
    has_date: false
    has_time: true

  octopus_power_up_end:
    name: Octopus Power-up end
    icon: "mdi:clock-end"
    has_date: false
    has_time: true

  octopus_power_up_date:
    name: Octopus Power-up date
    icon: "mdi:calendar"
    has_date: true
    has_time: false

input_number:
  octopus_power_up_max_soc:
    name: Octopus Power-up max SOC
    icon: "mdi:battery-40"
    min: 10
    max: 100
    step: 1
    mode: box

input_boolean:
  octopus_power_up_solar_export:
    name: Octopus Power-up solar export
    icon: "mdi:weather-sunny-alert"

  octopus_power_up_water_heater:
    name: Octopus Power-up use immersion heater
    icon: "mdi:thermometer-water"


## Sensors
template:
  - sensor:
    - name: Octopus Power-up overnight trigger time
      unique_id: sensor.octopus_power_up_overnight_trigger_time
      icon: "mdi:calendar"
      device_class: timestamp
      state: >-
        {{ ((states.input_datetime.octopus_power_up_date.attributes.timestamp - 1800) | as_datetime | as_local).isoformat() }}

    - name: Octopus Power-up slot start time
      unique_id: sensor.octopus_power_up_slot_start_time
      icon: "mdi:clock-start"
      device_class: timestamp
      state: >-
        {{ ((states.input_datetime.octopus_power_up_date.attributes.timestamp + states.input_datetime.octopus_power_up_start.attributes.timestamp)  | as_datetime | as_local).isoformat() }}

    - name: Octopus Power-up slot end time
      unique_id: sensor.octopus_power_up_slot_end_time
      icon: "mdi:clock-end"
      device_class: timestamp
      state: >-
        {{ ((states.input_datetime.octopus_power_up_date.attributes.timestamp + states.input_datetime.octopus_power_up_end.attributes.timestamp)  | as_datetime | as_local).isoformat() }}

  - binary_sensor:
    - name: Octopus Power-up active
      unique_id: binary_sensor.octopus_power_up_active
      icon: "mdi:power-plug-battery"
      state: >-
        {{ states.sensor.octopus_power_up_slot_end_time.state | as_datetime > now() > states.sensor.octopus_power_up_slot_start_time.state | as_datetime }}
    
    - name: Octopus Power-up pending
      unique_id: binary_sensor.octopus_power_up_pending
      icon: "mdi:power-plug-battery"
      state: >-
        {{ states.sensor.octopus_power_up_slot_end_time.state | as_datetime > now() }}


automation:
  - id: autidpowerupovernight
    alias: Octopus Power-up overnight configuration
    description: "Configures charge levels and modes, and prepares other devices for power up"
    trigger:
      - platform: time
        at: sensor.octopus_power_up_overnight_trigger_time
    condition: []
    action:
      - service: number.set_value
        data:
          value: "{{ states.input_number.octopus_power_up_max_soc.state | int }}"
        target:
          entity_id: number.max_soc
      - if:
          - condition: state
            entity_id: input_boolean.octopus_power_up_water_heater
            state: "on"
        then:
          - service: water_heater.set_away_mode
            data:
              away_mode: true
            target:
              entity_id: water_heater.dhw_controller
      - if:
          - condition: state
            entity_id: input_boolean.octopus_power_up_solar_export
            state: "on"
        then:
          - service: select.select_option
            data:
              option: Feed-in First
            target:
              entity_id: select.work_mode
    mode: single

  - id: autidpowerupstart
    alias: Octopus Power-up period start
    description: "Starts battery and car charging and enables other power-consuming devices"
    trigger:
      - platform: time
        at: sensor.octopus_power_up_slot_start_time
    condition: []
    action:
      - parallel:
          - service: foxess_modbus.update_charge_period
            data:
              inverter: bb431a8f0b4902c51fdb98acdc4a6c6a
              enable_force_charge: true
              enable_charge_from_grid: true
              start: >-
                {{states.sensor.octopus_power_up_slot_start_time.state | as_timestamp | 
                timestamp_custom('%H:%M:%S')}}
              end: >-
                {{states.sensor.octopus_power_up_slot_end_time.state | as_timestamp | 
                timestamp_custom('%H:%M:%S')}}
              charge_period: "1"
          - service: number.set_value
            data:
              value: "100"
            target:
              entity_id: number.max_soc
          - service: select.select_option
            data:
              option: Self Use
            target:
              entity_id: select.work_mode
          - if:
              - condition: state
                entity_id: binary_sensor.blue_shell_charger
                state: "on"
            then:
              - parallel:
                  - service: switch.turn_on
                    data: {}
                    target:
                      entity_id: switch.octopus_bump_charge
                  - service: switch.turn_on
                    data: {}
                    target:
                      entity_id: switch.blue_shell_charger
    mode: single

  - id: autidpowerupend
    alias: Octopus Power-up period end
    description: "Stops battery and car charging and reverts settings to normal"
    trigger:
      - platform: time
        at: sensor.octopus_power_up_slot_end_time
    condition: []
    action:
      - parallel:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.octopus_bump_charge
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.blue_shell_charger
          - service: foxess_modbus.update_charge_period
            data:
              inverter: bb431a8f0b4902c51fdb98acdc4a6c6a
              enable_force_charge: false
              enable_charge_from_grid: false
              start: '23:25:00'
              end: '23:25:00'
              charge_period: '1'
          - service: water_heater.set_operation_mode
            data:
              operation_mode: auto
            target:
              entity_id: water_heater.dhw_controller
    mode: single


## Customisations
homeassistant:
  customize:
    automation.octopus_power_up_period_start:
      icon: "mdi:battery-arrow-up"

    automation.octopus_power_up_period_end:  
      icon: "mdi:battery-arrow-down"

    automation.octopus_power_up_overnight_configuration:
      icon: "mdi:weather-night"
